application:
  title: SPRING-SECURITY-ACL
spring:
  #The way to resolve this issue (Swagger not working) is by adding pathmatcher in application. properties
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 9898
