application:
  title: SPRING-SECURITY-ACL

server:
  port: 9898

spring:
  #The way to resolve this issue (Swagger not working) is by adding pathmatcher in application. properties
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


