spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
  main:
#    allow-bean-definition-overriding: true
    allow-circular-references: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
