version: '3'

services:
  app:
    build:
      context: .
      dockerfile: exercise11.DockerFile
    restart: unless-stopped
    privileged: true
    environment:
      SPRING_DATASOURCE: jdbc:h2:mem:testdb