spring:

  messages:
    encoding: UTF-8

  datasource:
    url: jdbc:h2:mem:testdb

  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
